In [27]:
import pandas as pd
import sqlite3

In [28]:
# Load CSV
df = pd.read_csv("../data/cleaned/sales_records_enhanced.csv")

# Connect DB
conn = sqlite3.connect("../data/cleaned/dashiq.db")

In [29]:
python_revenue = df["Total Revenue"].sum()
python_revenue

np.float64(1262972839116.5498)

In [30]:
sql_revenue = pd.read_sql("""
SELECT SUM("Total Revenue") AS total_revenue
FROM fact_sales
""", conn)

sql_revenue

   total_revenue
0   1.262973e+12

In [31]:
print("Python:", python_revenue)
print("SQL:", sql_revenue["total_revenue"][0])

Python: 1262972839116.5498
SQL: 1262972839116.55

In [32]:
python_profit = df["Total Profit"].sum()

In [33]:
sql_profit = pd.read_sql("""
SELECT SUM("Total Profit") AS total_profit
FROM fact_sales
""", conn)

In [34]:
print("Python:", python_profit)
print("SQL:", sql_profit["total_profit"][0])

Python: 372665033991.87
SQL: 372665033991.87

In [35]:
df_2020 = df[df["Year"] == 2013]
df_2020["Total Revenue"].sum()

np.float64(166582842974.16998)

In [36]:
pd.read_sql("""
SELECT SUM("Total Revenue") AS total_revenue
FROM fact_sales
WHERE Year = 2013
""", conn)

   total_revenue
0   1.665828e+11

In [37]:
python_margin = df["Total Profit"].sum() / df["Total Revenue"].sum()
python_margin

np.float64(0.2950697136547682)

In [38]:
sql_margin = pd.read_sql("""
SELECT 
    SUM("Total Profit") * 1.0 / SUM("Total Revenue") AS profit_margin
FROM fact_sales
""", conn)

sql_margin

   profit_margin
0        0.29507

In [39]:
round(python_revenue, 2) == round(sql_revenue["total_revenue"][0], 2)

np.True_

In [40]:
conn.close()