In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/cleaned/sales_records_enhanced.csv")

df["Order Date"] = pd.to_datetime(df["Order Date"])
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Month,Year,Profit Margin,Profit Margin (%),Discount Bucket
0,Sub-Saharan Africa,South Africa,Fruits,Offline,M,2012-07-27,443368995,2012-07-28,1593,9.33,6.92,14862.69,11023.56,3839.13,7,2012,0.258307,25.830654,Medium Discount
1,Middle East And North Africa,Morocco,Clothes,Online,M,2013-09-14,667593514,2013-10-19,4611,109.28,35.84,503890.08,165258.24,338631.84,9,2013,0.672035,67.203514,Low Discount
2,Australia And Oceania,Papua New Guinea,Meat,Offline,M,2015-05-15,940995585,2015-06-04,360,421.89,364.69,151880.40,131288.40,20592.00,5,2015,0.135580,13.558036,Medium Discount
3,Sub-Saharan Africa,Djibouti,Clothes,Offline,H,2017-05-17,880811536,2017-07-02,562,109.28,35.84,61415.36,20142.08,41273.28,5,2017,0.672035,67.203514,Low Discount
4,Europe,Slovakia,Beverages,Offline,L,2016-10-26,174590194,2016-12-04,3973,47.45,31.79,188518.85,126301.67,62217.18,10,2016,0.330032,33.003161,Low Discount

In [3]:
monthly_sales = df.groupby(["Year", "Month"])["Total Revenue"].sum().reset_index()
monthly_sales.head()

   Year  Month  Total Revenue
0  2010      1   1.305167e+10
1  2010      2   1.221697e+10
2  2010      3   1.324689e+10
3  2010      4   1.302117e+10
4  2010      5   1.353405e+10

In [4]:
category_perf = df.groupby("Item Type")["Total Revenue"].sum().sort_values(ascending=False)
category_perf

#Total Profit by Item Type
df.groupby("Item Type")["Total Profit"].sum().sort_values(ascending=False)
#Units Sold by Item Type
df.groupby("Item Type")["Units Sold"].sum().sort_values(ascending=False)
#Revenue by Region
region_perf = df.groupby("Region")["Total Revenue"].sum().sort_values(ascending=False)
region_perf
#Profit by Region
df.groupby("Region")["Total Profit"].sum().sort_values(ascending=False)
#Revenue by discount bucket
df.groupby("Discount Bucket")["Total Revenue"].sum()
df.groupby("Discount Bucket")["Total Profit"].sum()
df.groupby("Discount Bucket")["Profit Margin"].mean()

Discount Bucket
Low Discount       0.410369
Medium Discount    0.209001
Name: Profit Margin, dtype: float64

In [5]:
df.groupby("Sales Channel")["Total Revenue"].sum()

Sales Channel
Offline    6.318761e+11
Online     6.310968e+11
Name: Total Revenue, dtype: float64